export enum EConfigKeys {
  AMQP = 'amqp',
  AMQP_URL = 'amqp.url',
  MONGO_URL = 'mongo.url',
  MONGO_DB = 'mongo.db',
  MONGO_TEST_DB = 'mongo.testDb',
  CORS_ORIGIN = 'corsOrigin',
  MY_ADDRESS = 'myAddress',
  MY_DOMAIN = 'myDomain',
  AUTHORIZATION_ADDRESS = 'authorizationAddress',
  AUTHORIZATION_INNER_ADDRESS = 'authorizationInnerAddress',
  HTTP_PORT = 'httpPort',
  SOCKET_PORT = 'socketPort',
  REDIS_URL = 'redisURL',
  SESSION_SECRET = 'session.secret',
  SESSION_SECURED = 'session.secured',
  SESSION_TRUST_PROXY = 'session.trustProxy',
  METRICS_LOKI = 'metrics.loki',
  REPOSITORY = 'repository',
  TOKENS_DOMAIN = 'tokens.domain',
}

export enum EConfigEnvs {
  AMQP = 'AMQP',
  AMQP_URL = 'AMQP_URL',
  MONGO_URL = 'MONGO_URL',
  MONGO_DB = 'MONGO_DB',
  MONGO_TEST_DB = 'MONGO_TEST_DB',
  CORS_ORIGIN = 'CORS_ORIGIN',
  MY_ADDRESS = 'MY_ADDRESS',
  MY_DOMAIN = 'MY_DOMAIN',
  AUTHORIZATION_ADDRESS = 'AUTHORIZATION_ADDRESS',
  AUTHORIZATION_INNER_ADDRESS = 'AUTHORIZATION_INNER_ADDRESS',
  HTTP_PORT = 'HTTP_PORT',
  SOCKET_PORT = 'SOCKET_PORT',
  REDIS_URL = 'REDIS_URL',
  SESSION_SECRET = 'SESSION_SECRET',
  SESSION_SECURED = 'SESSION_SECURED',
  SESSION_TRUST_PROXY = 'SESSION_TRUST_PROXY',
  METRICS_LOKI = 'METRICS_LOKI',
  REPOSITORY = 'REPOSITORY',
  TOKENS_DOMAIN = 'TOKENS_DOMAIN',
}
